services:
  - type: web
    name: springboot-backend
    runtime: docker
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:+UseContainerSupport
    
